site_name: OpenMFD Documentation
docs_dir: docs2

dev_addr: '127.0.0.1:5000'

nav:
  - "Home": index.md
  - "Table of Contents": 0-TOC.md
  - "Main Tutorial":
      - "Part 1: Introduction": 1-introduction.md
      - "Part 2: Installation": 2-installation.md
      - "Part 3: Using the Visualizer": 3-visualizer.md
      - "Part 4: Creating Your First Component": 4-building_first_component.md
      - "Part 5: Working with Polychannels": 5-polychannel.md
      - "Part 6: Integrating Subcomponents": 6-subcomponents.md
      - "Part 7: Routing": 7-routing.md
      - "Part 8: Designing Custom Subcomponents": 8-making_subcomponent.md
      - "Part 9: Creating Your First Slicable Device": 9-slicer_settings.md
      - "Part 10: Slicing Process": 10-slicing.md
      - "Part 11: Interpreting Slicer Output": 11-slicer_output.md
      - "Part 12: Configuring Regional Settings": 12-regional_settings.md
  - "Advanced Topics":
      - "Extra 1: Customizing Subcomponent Labels and Colors": e1-recoloring_components.md
      - "Extra 2: Variable Layer Thickness Components": e2-variable_layer_thickness_components.md
      - "Extra 3: Device Stitching": e3-stitching.md
      - "Extra 4: Device Embedding": e4-embedding.md
      - "Extra 5: Advanced TPMS Grid Structures": e5-tpms_grids.md
      - "Extra 6: Specialized Printing Techniques": e6-special_cases.md
  - "Resources":
      - "Cheat Sheet for OpenMFD": r1-cheatsheet.md
      - "Named Color Lists": r2-color.md
      - "Custom Component Template": r3-component_template.md
      - "JSON Print File Reference": r4-json_print_file_reference.md

theme: readthedocs

markdown_extensions:
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.arithmatex:
            generic: true

extra_javascript:
    - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
    - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
    - javascripts/katex.js

extra_css:
    - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css
