site_name: OpenMFD Documentation
site_url: https://openmfd.readthedocs.io/latest/
docs_dir: docs
site_dir: src/openmfd/site/docs
use_directory_urls: false

dev_addr: '127.0.0.1:5000'

nav:
  - "Home": index.md
  - "Main Tutorial":
      - "Part 1: Introduction": 1-introduction.md
      - "Part 2: Installation": 2-installation.md
      - "Part 3: Using the Visualizer": 3-visualizer.md
      - "Part 4: Hello World Component": 4-building_first_component.md
      - "Part 5: Shapes and Operations": 5-shapes_operations.md
      - "Part 6: Parametric Design": 6-parametric_design.md
      - "Part 7: Working with Polychannels": 5-polychannel.md
      - "Part 8: Integrating Subcomponents": 6-subcomponents.md
      - "Part 9: Routing": 7-routing.md
      - "Part 10: Designing Custom Subcomponents": 8-making_subcomponent.md
      - "Part 11: Creating Your First Slicable Device": 9-slicer_settings.md
      - "Part 12: Slicing Process": 10-slicing.md
      - "Part 13: Interpreting Slicer Output": 11-slicer_output.md
      - "Part 14: Configuring Regional Settings": 12-regional_settings.md
  - "Advanced Topics":
      - "Extra 1: Customizing Subcomponent Labels and Colors": e1-recoloring_components.md
      - "Extra 2: Variable Layer Thickness Components": e2-variable_layer_thickness_components.md
      - "Extra 3: Device Stitching": e3-stitching.md
      - "Extra 4: Device Embedding": e4-embedding.md
      - "Extra 5: Advanced TPMS Grid Structures": e5-tpms_grids.md
      - "Extra 6: Specialized Printing Techniques": e6-special_cases.md
      - "Extra 7: Advanced Visualizer Topics": e7-visualizer_advanced.md
  - "Resources":
      - "Cheat Sheet for OpenMFD": r1-cheatsheet.md
      - "Named Color Lists": r2-color.md
      - "Custom Component Template": r3-component_template.md
      - "JSON Print File Reference": r4-json_print_file_reference.md
      - "AI Integration Guide": r5-ai_integration.md
  - "API Reference":
      - "Core": api/core.md
      - "Component/Device": api/component.md
      - "Color": api/color.md
      - "Shape": api/shapes.md
      - "Port": api/port.md
      - "Polychannel": api/polychannels.md
      - "Router": api/router.md
      - "Settings": api/settings.md
      - "Special Techniques": api/special_techniques.md
      - "Slicer": api/slicer.md
      - "Component Library": api/component_library.md


theme: readthedocs

markdown_extensions:
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.arithmatex:
            generic: true

plugins:
    - search
    - mkdocstrings:
          handlers:
            python:
              options:
                show_source: false
                show_root_heading: true
                show_root_full_path: false
                separate_signature: true
                show_signature_annotations: true
                show_if_no_docstring: false
                docstring_style: google
                docstring_section_style: list
                heading_level: 3

extra_javascript:
    - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
    - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
    - static/katex.js

extra_css:
    - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css
    - static/custom.css
